import type { NextConfig } from 'next';
const nextConfig: NextConfig = {
 distDir: process.env.NEXT_BUILD_DIR || '.next',
 reactStrictMode: true,
 eslint: { ignoreDuringBuilds: true },
 images: { unoptimized: true },
 async headers() { return [
  { source: "/admin/:path*", headers: [{ key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" }] },
  { source: "/thank-you", headers: [{ key: "X-Robots-Tag", value: "noindex, noarchive" }] },
  { source: "/all-pages", headers: [{ key: "X-Robots-Tag", value: "noindex, follow" }] }
 ]; },
 async redirects() { return [
  { source: "/bangalore", destination: "/", permanent: true },
  { source: "/bangalore/destinations", destination: "/bangalore/destinations/makkah", permanent: true },
  { source: "/services/full-home", destination: "/bangalore/services/umrah-packages", permanent: true },
  { source: "/bangalore/services/full-home", destination: "/bangalore/services/umrah-packages", permanent: true },
  { source: "/services/modular-kitchen", destination: "/bangalore/services/hajj-enquiries", permanent: true },
  { source: "/bangalore/services/modular-kitchen", destination: "/bangalore/services/hajj-enquiries", permanent: true },
  { source: "/services/wardrobes", destination: "/bangalore/services/family-umrah", permanent: true },
  { source: "/bangalore/services/wardrobes", destination: "/bangalore/services/family-umrah", permanent: true },
  { source: "/services/living-room", destination: "/bangalore/services/group-umrah", permanent: true },
  { source: "/bangalore/services/living-room", destination: "/bangalore/services/group-umrah", permanent: true },
  { source: "/services/bedroom", destination: "/bangalore/services/private-umrah", permanent: true },
  { source: "/bangalore/services/bedroom", destination: "/bangalore/services/private-umrah", permanent: true },
  { source: "/services/bathroom", destination: "/bangalore/services/makkah-madinah-stays", permanent: true },
  { source: "/bangalore/services/bathroom", destination: "/bangalore/services/makkah-madinah-stays", permanent: true },
  { source: "/services/false-ceiling", destination: "/bangalore/services/flights-transfers", permanent: true },
  { source: "/bangalore/services/false-ceiling", destination: "/bangalore/services/flights-transfers", permanent: true },
  { source: "/services/tv-unit", destination: "/bangalore/services/visa-assistance", permanent: true },
  { source: "/bangalore/services/tv-unit", destination: "/bangalore/services/visa-assistance", permanent: true },
  { source: "/services/pooja-room", destination: "/bangalore/services/ziyarat", permanent: true },
  { source: "/bangalore/services/pooja-room", destination: "/bangalore/services/ziyarat", permanent: true },
  { source: "/services/renovation", destination: "/bangalore/services/ramadan-umrah", permanent: true },
  { source: "/bangalore/services/renovation", destination: "/bangalore/services/ramadan-umrah", permanent: true },
  { source: "/services/commercial", destination: "/bangalore/services/muslim-friendly-holidays", permanent: true },
  { source: "/bangalore/services/commercial", destination: "/bangalore/services/muslim-friendly-holidays", permanent: true },
  { source: "/portfolio/kitchen", destination: "/bangalore/destinations/makkah", permanent: true },
  { source: "/bangalore/portfolio/kitchen", destination: "/bangalore/destinations/makkah", permanent: true },
  { source: "/portfolio/bedroom", destination: "/bangalore/destinations/madinah", permanent: true },
  { source: "/bangalore/portfolio/bedroom", destination: "/bangalore/destinations/madinah", permanent: true },
  { source: "/portfolio/living-room", destination: "/bangalore/destinations/umrah-journeys", permanent: true },
  { source: "/bangalore/portfolio/living-room", destination: "/bangalore/destinations/umrah-journeys", permanent: true },
  { source: "/portfolio/wardrobe", destination: "/bangalore/destinations/family-travel", permanent: true },
  { source: "/bangalore/portfolio/wardrobe", destination: "/bangalore/destinations/family-travel", permanent: true },
  { source: "/portfolio/bathroom", destination: "/bangalore/destinations/ziyarat-visits", permanent: true },
  { source: "/bangalore/portfolio/bathroom", destination: "/bangalore/destinations/ziyarat-visits", permanent: true },
  { source: "/portfolio/study-room", destination: "/bangalore/destinations/travel-preparation", permanent: true },
  { source: "/bangalore/portfolio/study-room", destination: "/bangalore/destinations/travel-preparation", permanent: true },
  { source: "/project-type/2bhk", destination: "/bangalore/packages/umrah", permanent: true },
  { source: "/bangalore/project-type/2bhk", destination: "/bangalore/packages/umrah", permanent: true },
  { source: "/project-type/3bhk", destination: "/bangalore/packages/family-umrah", permanent: true },
  { source: "/bangalore/project-type/3bhk", destination: "/bangalore/packages/family-umrah", permanent: true },
  { source: "/project-type/4bhk", destination: "/bangalore/packages/group-umrah", permanent: true },
  { source: "/bangalore/project-type/4bhk", destination: "/bangalore/packages/group-umrah", permanent: true },
  { source: "/project-type/penthouse", destination: "/bangalore/packages/private-umrah", permanent: true },
  { source: "/bangalore/project-type/penthouse", destination: "/bangalore/packages/private-umrah", permanent: true },
  { source: "/projects/2bhk-apartment", destination: "/bangalore/journeys/classic-umrah", permanent: true },
  { source: "/bangalore/projects/2bhk-apartment", destination: "/bangalore/journeys/classic-umrah", permanent: true },
  { source: "/projects/luxury-villa", destination: "/bangalore/journeys/private-family-umrah", permanent: true },
  { source: "/bangalore/projects/luxury-villa", destination: "/bangalore/journeys/private-family-umrah", permanent: true },
  { source: "/projects/3bhk-penthouse", destination: "/bangalore/journeys/makkah-madinah", permanent: true },
  { source: "/bangalore/projects/3bhk-penthouse", destination: "/bangalore/journeys/makkah-madinah", permanent: true },
  { source: "/projects/modular-kitchen-project", destination: "/bangalore/journeys/ramadan-umrah", permanent: true },
  { source: "/bangalore/projects/modular-kitchen-project", destination: "/bangalore/journeys/ramadan-umrah", permanent: true },
  { source: "/projects/master-bedroom", destination: "/bangalore/journeys/small-group-umrah", permanent: true },
  { source: "/bangalore/projects/master-bedroom", destination: "/bangalore/journeys/small-group-umrah", permanent: true },
  { source: "/projects/living-room-makeover", destination: "/bangalore/journeys/muslim-friendly-holiday", permanent: true },
  { source: "/bangalore/projects/living-room-makeover", destination: "/bangalore/journeys/muslim-friendly-holiday", permanent: true },
  { source: "/2bhk-interior-design-cost-bangalore", destination: "/umrah-package-guide-bangalore", permanent: true },
  { source: "/3bhk-interior-design-cost-bangalore", destination: "/family-umrah-package-guide-bangalore", permanent: true },
  { source: "/interior-design-cost", destination: "/bangalore/travel-package-guide", permanent: true },
  { source: "/bangalore/interior-design-cost", destination: "/bangalore/travel-package-guide", permanent: true },
  { source: "/project-type", destination: "/packages", permanent: true },
  { source: "/bangalore/project-type", destination: "/bangalore/packages", permanent: true },
  { source: "/portfolio", destination: "/bangalore/destinations/makkah", permanent: true },
  { source: "/bangalore/portfolio", destination: "/bangalore/destinations/makkah", permanent: true },
  { source: "/projects", destination: "/journeys", permanent: true },
  { source: "/bangalore/projects", destination: "/bangalore/journeys", permanent: true },
  { source: "/bengaluru", destination: "/bangalore", permanent: true },
  { source: "/bengaluru/:path*", destination: "/bangalore/:path*", permanent: true },
  { source: "/area/:path*", destination: "/bangalore/:path*", permanent: true },
  { source: "/services", destination: "/bangalore/services", permanent: true },
  { source: "/services/:path*", destination: "/bangalore/services/:path*", permanent: true },
  { source: "/journeys", destination: "/bangalore/journeys", permanent: true },
  { source: "/journeys/:path*", destination: "/bangalore/journeys/:path*", permanent: true },
  { source: "/destinations", destination: "/bangalore/destinations/makkah", permanent: true },
  { source: "/destinations/:path*", destination: "/bangalore/destinations/:path*", permanent: true },
  { source: "/packages", destination: "/bangalore/packages", permanent: true },
  { source: "/packages/:path*", destination: "/bangalore/packages/:path*", permanent: true },
  { source: "/travel-package-guide", destination: "/bangalore/travel-package-guide", permanent: true }
]; }
};
export default nextConfig;
